### ISSUE TITLE
activate-tab-on-hover.js stopped working on Vivaldi.6.10.3464.3.x64

### ISSUE THREAD

**Issue by Janaue** [luetage/vivaldi_modding#11]
hello, I've just updated my vivaldi beta to Vivaldi.6.10.3464.3.x64 on windows and I can't get activate-tab-on-hover.js to work. It's the only script i use and the profile is completely stock.

**Comment by luetage** [comment]
They apparently added an additional parent node. Should work now.

**Comment by luetage** [comment]
@Janaue gonna close this, works for me on 6.10 now.
