### ISSUE TITLE
Activate Tab on Hover - Problem in vertical tab bar

### ISSUE THREAD

**Issue by N3C2L** [luetage/vivaldi_modding#7]
Thanks again for the tab stack update. Works fine.
However, I have another problem. If you activate the vertical tab bar (e.g. left) and then move the mouse pointer all the way to the left edge of the screen and move the mouse up and down between the tabs, the tabs will not activate by hover. But if you click with the mouse, these tabs get activate. I don't know if it's because of my browser.

**Comment by luetage** [comment]
Hey, just tried it and can’t reproduce. It doesn’t make much sense, because the event listeners are on the tabs and get triggered whenever you hover them. Clicking or dragging outside can’t deactivate them. No idea what’s going on on your end, but I won’t be able to fix it.

**Comment by N3C2L** [comment]
Thanks. Hmm. When I put the tab bar above the adress bar it works if I move the mouse pointer alle the way up to the screen and between the tabs. At first I thought it was caused by the fact that I have a high zoom level of 200% in Windows 10 (because my monitor is far away). But that is not the cause. Switchted to 125% same problem. But my UI zoom level in Vivaldi is set to 90%. Does not change the vertical tabs switching problem if I increase or decrease the zoom level. Need to investigate further..

**Comment by N3C2L** [comment]
![2021-03-16 14_45_46-Greenshot](https://user-images.githubusercontent.com/74585843/111319788-a94b4280-8666-11eb-9c46-151301b4fcc3.png)

Look at the pic. Do you also have this margin to the left of the tab? I think this margin is the reason why it will not activate the tab if the cursor is far left in the screen like in my picture.

**Comment by N3C2L** [comment]
Can you add some CSS into your javascript that removes this left margin from tabs/tab bar? So that new user of the this script will not ask for this question again.

**Comment by luetage** [comment]
Didn’t know you aren’t showing the panel. I disabled my panel, made the tabs small like yours and tried again. I have zero issues. You will have to come up with a solution yourself.

**Comment by luetage** [comment]
Maybe someone on Vivaldi Forum can help you, or at least reproduce. Please follow the link on top of the mod and make a post there.

**Comment by N3C2L** [comment]
Ok, just to clarify:

1. you do not have this margin and it is working or
2. you have this margin and it is working?
3. if you move the cursor from one left margin of a tab straight above to the next left margin of a tab, the tab gets activated with hovering?

**Comment by luetage** [comment]
Around the edge my cursor changes shape and is ready to resize the window, this cannot trigger the mod and I do not consider it a bug. Should the margin make trouble for you, you can of course remove it with CSS, you don’t need Javascript.

**Comment by N3C2L** [comment]
If the Vivaldi window is maximized then the cursor does not change into resize. At least on Windows 10. Maybe you are on another OS and there is another behavior. On my pic above you see a cutout of the maximized window and the cursor is at the left edge of the screen, no cursor change into resize.

**Comment by luetage** [comment]
I’m on Linux and not questioning your issue, but you have to understand that it’s a very specific and personal one, no one but you needs that change. Removing the margin alters Vivaldi’s looks and I’m not willing to change it for everyone else. My suggestion is you create a custom.css file and remove the margin. Here a guide how to inspect the UI: [https://forum.vivaldi.net/topic/16684/inspecting-the-vivaldi-ui-with-devtools](https://forum.vivaldi.net/topic/16684/inspecting-the-vivaldi-ui-with-devtools)

**Comment by N3C2L** [comment]
Yes, I know it can be cut with css. But I thought that you may have a better solution.
When you click with the left mouse button in this left margin outside the tab it gets activated, but not if you hover over them. So I just wondered why you can click outside there and the tab gets activated.. there must something trigger these tabs in this margin with the mouse click that your hoverscript not detect as tab area..

**Comment by luetage** [comment]
The click probably bubbles through. I won’t do anything about this.

**Comment by N3C2L** [comment]
OK I will close this now, unsolved, maybe someday you will emulate Windows 10 for users who have problems there.
