### ISSUE TITLE
Mod request: Activate Web Panel by Hover

### ISSUE THREAD

**Issue by lifehaschanged** [luetage/vivaldi_modding#8]
Greetings luetage,

big respect to you, love your mods, but can`t code myself. Saw on Vivaldi Forum that you have made the marvelous activate Tab by Hover script. Because I want to prevent furthermore from Repetetive strain injury (Clicking by mouse or texting with keyboard sometimes hurts my fingers) I would love to see a Mod that activates Web panels by Hovering.
What do you think?

**Comment by luetage** [comment]
Hoi, maybe I take a look at it, no promises. You get higher chances of your wish being fulfilled, if you post your request on the modifications forum board – someone else might get to it sooner. Or perhaps it already exists and someone can link you.

**Comment by lifehaschanged** [comment]
Thanks for these tips. I forgot searching the Vivaldi forum.
In the following thread I found it. Now hovering opens web panels:

https://forum.vivaldi.net/topic/28413/open-panels-on-mouse-over/63?lang=de&page=4
